# Generated by Django 3.0.6 on 2020-06-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20200602_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar_url',
            new_name='avatar',
        ),
    ]
